from .variables import *

VARIABLES = Variables()

VERSION = "v0.0.1"
GAME_NAME = "Laser Tag"

WINDOW_WINDOWED_SIZE_RATIO = 0.75

TARGET_FPS = 60

NETWORK_BUFFER_SIZE = 1024
SERVER_TIMEOUT = 10
SERVER_SOCKET_TIMEOUT = 2
CLIENT_TIMEOUT = 5

SCREENSHOTS_PATH = "./screenshots"
