from .variables import *

VARIABLES = Variables()

VERSION = "v0.0.6"
GAME_NAME = "Laser Tag"

WINDOW_WINDOWED_SIZE_RATIO = 0.75

TARGET_FPS = 60

NETWORK_BUFFER_SIZE = 32768
SERVER_TIMEOUT = 10
SERVER_SOCKET_TIMEOUT = 2
CLIENT_TIMEOUT = 5
DEFAULT_MAX_CLIENTS = None

SERVER_DELTA_TIME_NAME = "SERVER"

SCREENSHOTS_PATH = "./screenshots"
