from .variables import *

VARIABLES = Variables()

VERSION = "v0.0.3"
GAME_NAME = "Laser Tag"

WINDOW_WINDOWED_SIZE_RATIO = 0.75

TARGET_FPS = 60

NETWORK_BUFFER_SIZE = 2048
SERVER_TIMEOUT = 10
SERVER_SOCKET_TIMEOUT = 2
CLIENT_TIMEOUT = 5
DEFAULT_MAX_CLIENTS = None

SCREENSHOTS_PATH = "./screenshots"
